# SPDX-License-Identifier: Apache-2.0
---

# Facts are not set here to ensure that they do not influence other plan steps,
# instead they are set temporarily in vars section of include_tasks.

- name: SAP Patching - Web Dispatcher - Saproot - Execute shared tasks for kernel saproot
  ansible.builtin.include_tasks:
    file: common/shared_kernel_saproot.yml
  vars:
    __sap_patching_fact_sap_system_sid: "{{ (sap_patching_wdp_system_sid | d(sap_patching_sap_system_sid)) | upper }}"
